import { supabase } from "../src/utils/supabase";

const wordPacks = [
  {
    name: "Animals",
    emoji: "🐾",
    category: "Animals",
    words: [
      "dog",
      "cat",
      "elephant",
      "dolphin",
      "parrot",
      "shark",
      "tiger",
      "giraffe",
      "penguin",
      "kangaroo",
      "cobra",
      "flamingo",
      "wolf",
      "fox",
      "panda",
      "gorilla",
      "crocodile",
      "eagle",
      "octopus",
      "cheetah",
      "hamster",
      "iguana",
      "jellyfish",
      "koala",
      "llama",
      "manta ray",
      "narwhal",
      "orangutan",
      "peacock",
      "quokka",
      "raccoon",
      "sloth",
      "toucan",
      "unicorn fish",
      "vulture",
      "walrus",
      "xerus",
      "yak",
      "zebrafish",
      "axolotl",
      "bison",
      "capybara",
    ],
  },
  {
    name: "Food",
    emoji: "🍕",
    category: "Food",
    words: [
      "pizza",
      "sushi",
      "burger",
      "pasta",
      "tacos",
      "ramen",
      "steak",
      "croissant",
      "cheesecake",
      "hotdog",
      "nachos",
      "curry",
      "paella",
      "pho",
      "dim sum",
      "falafel",
      "gelato",
      "kimchi",
      "lasagna",
      "mochi",
      "noodles",
      "oyster",
      "pretzel",
      "quinoa",
      "risotto",
      "samosa",
      "tiramisu",
      "udon",
      "vindaloo",
      "waffle",
      "fondue",
      "gyoza",
      "hummus",
      "ice cream",
      "jerk chicken",
      "kebab",
      "lemon tart",
      "macaroon",
      "naan",
      "omelette",
    ],
  },
  {
    name: "Countries",
    emoji: "🌍",
    category: "Countries",
    words: [
      "France",
      "Japan",
      "Brazil",
      "Egypt",
      "Canada",
      "India",
      "Australia",
      "Mexico",
      "Germany",
      "Italy",
      "Russia",
      "China",
      "USA",
      "Argentina",
      "Nigeria",
      "South Korea",
      "Spain",
      "Turkey",
      "Netherlands",
      "Sweden",
      "Norway",
      "Saudi Arabia",
      "Pakistan",
      "Thailand",
      "Vietnam",
      "Poland",
      "Ukraine",
      "Colombia",
      "Kenya",
      "Morocco",
    ],
  },
  {
    name: "Cities",
    emoji: "🏙️",
    category: "Cities",
    words: [
      "Paris",
      "Tokyo",
      "New York",
      "Dubai",
      "London",
      "Sydney",
      "Rome",
      "Berlin",
      "Mumbai",
      "Seoul",
      "Cairo",
      "Rio",
      "Toronto",
      "Istanbul",
      "Bangkok",
      "Barcelona",
      "Amsterdam",
      "Singapore",
      "Lagos",
      "Karachi",
      "Cape Town",
      "Chicago",
      "Miami",
      "Hong Kong",
      "Zurich",
      "Vienna",
      "Lisbon",
      "Athens",
      "Prague",
      "Budapest",
    ],
  },
  {
    name: "Movies",
    emoji: "🎬",
    category: "Movies",
    words: [
      "Titanic",
      "Avatar",
      "Inception",
      "Interstellar",
      "Joker",
      "Avengers",
      "Frozen",
      "Lion King",
      "Matrix",
      "Gladiator",
      "Parasite",
      "Shrek",
      "Toy Story",
      "Batman",
      "Jurassic Park",
      "Forrest Gump",
      "Godfather",
      "Casablanca",
      "Jaws",
      "Psycho",
      "Pulp Fiction",
      "Goodfellas",
      "Fight Club",
      "Schindler's List",
      "Lord of the Rings",
      "Harry Potter",
      "Star Wars",
      "Indiana Jones",
      "Back to the Future",
      "Die Hard",
    ],
  },
  {
    name: "Music",
    emoji: "🎵",
    category: "Music",
    words: [
      "guitar",
      "microphone",
      "piano",
      "drums",
      "violin",
      "saxophone",
      "trumpet",
      "bass",
      "DJ",
      "vinyl record",
      "concert",
      "headphones",
      "lyrics",
      "melody",
      "chord",
      "riff",
      "solo",
      "orchestra",
      "beatbox",
      "karaoke",
      "conductor",
      "synthesizer",
      "ukulele",
      "flute",
      "cello",
      "trombone",
      "oboe",
      "harp",
      "banjo",
      "accordion",
    ],
  },
  {
    name: "Nature",
    emoji: "🌿",
    category: "Nature",
    words: [
      "mountain",
      "ocean",
      "volcano",
      "forest",
      "desert",
      "river",
      "glacier",
      "waterfall",
      "tornado",
      "rainbow",
      "thunder",
      "fog",
      "coral reef",
      "cave",
      "canyon",
      "tundra",
      "swamp",
      "meadow",
      "fjord",
      "geyser",
      "lagoon",
      "mangrove",
      "oasis",
      "plateau",
      "quicksand",
      "ravine",
      "savanna",
      "tide pool",
      "underbrush",
      "valley",
    ],
  },
  {
    name: "Science",
    emoji: "🔬",
    category: "Science",
    words: [
      "gravity",
      "DNA",
      "atom",
      "black hole",
      "evolution",
      "photosynthesis",
      "magnetism",
      "bacteria",
      "electricity",
      "telescope",
      "microscope",
      "vaccine",
      "quantum",
      "laser",
      "neutron",
      "supernova",
      "molecule",
      "element",
      "fossil",
      "enzyme",
      "hypothesis",
      "inertia",
      "kinetic energy",
      "lunar eclipse",
      "metamorphosis",
      "nucleus",
      "orbit",
      "parasite",
      "radioactive",
      "spectrum",
    ],
  },
  {
    name: "Celebrities",
    emoji: "⭐",
    category: "Celebrities",
    words: [
      "Elon Musk",
      "Taylor Swift",
      "LeBron James",
      "Beyoncé",
      "Tom Cruise",
      "Oprah",
      "Cristiano Ronaldo",
      "Rihanna",
      "Barack Obama",
      "Adele",
      "Lionel Messi",
      "Lady Gaga",
      "Drake",
      "Serena Williams",
      "Will Smith",
      "Kim Kardashian",
      "Jeff Bezos",
      "Shakira",
      "Usain Bolt",
      "Billie Eilish",
      "Kanye West",
      "Scarlett Johansson",
      "Dwayne Johnson",
      "Ariana Grande",
      "Zendaya",
      "Harry Styles",
    ],
  },
  {
    name: "Cars",
    emoji: "🚗",
    category: "Cars",
    words: [
      "Ferrari",
      "Lamborghini",
      "Tesla",
      "Porsche",
      "BMW",
      "Mercedes",
      "Toyota",
      "Ford Mustang",
      "Bugatti",
      "Rolls Royce",
      "Audi",
      "Jeep",
      "Corvette",
      "Dodge Viper",
      "McLaren",
      "Bentley",
      "Maserati",
      "Jaguar",
      "Land Rover",
      "Pagani Huayra",
      "Koenigsegg",
      "Alfa Romeo",
      "Cadillac",
      "Chevrolet",
      "Volvo",
      "Subaru",
      "Mazda",
      "Honda",
      "Hyundai",
      "Kia",
    ],
  },
  {
    name: "Gaming",
    emoji: "🎮",
    category: "Gaming",
    words: [
      "Minecraft",
      "Fortnite",
      "FIFA",
      "Call of Duty",
      "GTA",
      "Zelda",
      "Mario",
      "Pokemon",
      "Halo",
      "Roblox",
      "Among Us",
      "Cyberpunk",
      "God of War",
      "Elden Ring",
      "Red Dead Redemption",
      "Overwatch",
      "League of Legends",
      "Valorant",
      "Counter Strike",
      "Apex Legends",
      "Clash of Clans",
      "Candy Crush",
      "Tetris",
      "Pac-Man",
      "Sonic",
      "Kirby",
      "Donkey Kong",
      "Mega Man",
      "Street Fighter",
      "Mortal Kombat",
    ],
  },
  {
    name: "Anime",
    emoji: "🎌",
    category: "Anime",
    words: [
      "Naruto",
      "Dragon Ball Z",
      "One Piece",
      "Attack on Titan",
      "Death Note",
      "Demon Slayer",
      "My Hero Academia",
      "Bleach",
      "Fullmetal Alchemist",
      "Tokyo Ghoul",
      "Hunter x Hunter",
      "Sword Art Online",
      "Jujutsu Kaisen",
      "One Punch Man",
      "Spirited Away",
      "Princess Mononoke",
      "Your Name",
      "Cowboy Bebop",
      "Neon Genesis Evangelion",
      "Re:Zero",
      "Overlord",
      "Black Clover",
      "Fairy Tail",
      "Seven Deadly Sins",
      "Haikyuu",
      "Kuroko's Basketball",
      "Free!",
      "Ouran High School Host Club",
      "Sailor Moon",
      "Cardcaptor Sakura",
    ],
  },
  {
    name: "K-Pop",
    emoji: "🎤",
    category: "K-Pop",
    words: [
      "BTS",
      "BLACKPINK",
      "EXO",
      "Twice",
      "NCT",
      "Stray Kids",
      "aespa",
      "ITZY",
      "Monsta X",
      "GOT7",
      "iKON",
      "ATEEZ",
      "TXT",
      "Enhypen",
      "New Jeans",
      "Red Velvet",
      "Girls Generation",
      "SHINee",
      "Super Junior",
      "2NE1",
      "CL",
      "G-Dragon",
      "Taeyang",
      "IU",
      "Sunmi",
      "HyunA",
      "Zico",
      "Jay Park",
      "PSY",
      "BigBang",
    ],
  },
  {
    name: "Superheroes",
    emoji: "🦸",
    category: "Superheroes",
    words: [
      "Spider-Man",
      "Batman",
      "Superman",
      "Iron Man",
      "Wonder Woman",
      "Thor",
      "Captain America",
      "Black Panther",
      "Hulk",
      "Flash",
      "Wolverine",
      "Aquaman",
      "Doctor Strange",
      "Black Widow",
      "Hawkeye",
      "Ant-Man",
      "Deadpool",
      "Green Lantern",
      "Shazam",
      "Cyborg",
      "Vision",
      "Scarlet Witch",
      "Falcon",
      "War Machine",
      "Bucky",
      "Groot",
      "Rocket",
      "Star-Lord",
      "Gamora",
      "Drax",
    ],
  },
  {
    name: "Football",
    emoji: "⚽",
    category: "Football",
    words: [
      "Messi",
      "Ronaldo",
      "Neymar",
      "Mbappé",
      "Haaland",
      "Salah",
      "Benzema",
      "De Bruyne",
      "Modric",
      "Lewandowski",
      "Xavi",
      "Iniesta",
      "Zidane",
      "Beckham",
      "Rooney",
      "Cantona",
      "Pele",
      "Maradona",
      "Ronaldinho",
      "Roberto Carlos",
      "Pirlo",
      "Totti",
      "Del Piero",
      "Buffon",
      "Casillas",
      "Neuer",
      "Lahm",
      "Alves",
      "Ramos",
      "Terry",
    ],
  },
  {
    name: "Make-up",
    emoji: "💄",
    category: "Make-up",
    words: [
      "foundation",
      "mascara",
      "lipstick",
      "eyeliner",
      "blush",
      "highlighter",
      "concealer",
      "bronzer",
      "eyeshadow",
      "primer",
      "contour",
      "setting spray",
      "lip gloss",
      "powder",
      "toner",
      "serum",
      "moisturizer",
      "BB cream",
      "false lashes",
      "brow pencil",
      "makeup brush",
      "beauty blender",
      "palette",
      "pigment",
      "shimmer",
      "glitter",
      "matte",
      "dewy",
      "bold lip",
      "smoky eye",
    ],
  },
  {
    name: "Nostalgia",
    emoji: "🌟",
    category: "Nostalgia",
    words: [
      "Walkman",
      "cassette tape",
      "floppy disk",
      "VHS",
      "Game Boy",
      "Tamagotchi",
      "dial-up internet",
      "MySpace",
      "Napster",
      "Blockbuster",
      "pager",
      "payphone",
      "polaroid",
      "beeper",
      "Saturday cartoons",
      "jelly shoes",
      "slap bracelet",
      "frosted tips",
      "lunchable",
      "Oregon Trail",
      "AIM messenger",
      "CD ROM",
      "Snake game",
      "Furby",
      "Power Rangers",
      "Animaniacs",
      "Alf",
      "Cabbage Patch Kids",
      "Lite-Brite",
      "Pog",
    ],
  },
];

const seed = async () => {
  const { error } = await supabase
    .from("word_packs")
    .upsert(wordPacks, { onConflict: "name" });

  if (error) {
    console.error("Seed failed", error);
    process.exit(1);
  }

  console.log("Seed complete");
  process.exit(0);
};

seed();
